### ISSUE TITLE
新功能：统一环境信息配置

### ISSUE THREAD

**Issue by ictchenbo** [ictchenbo/SmartETL#5]
场景描述：
在实际开发工作中，需要有一批数据库的配置（重要的是密码！），比如mysql mongo es clickhouse等等。如果每个流程都写一遍，是不是很不方便，且容易乱掉，不好维护这个配置信息。

需求：如何能够统一环境信息配置？通过命令行参数或者某个yaml指令进行引用？

**Comment by ictchenbo** [comment]
已实现。
支持在yaml中添加 `**from**` 指令，建议在本地建立一个 `env.yaml` 文件，里面只需要包含环境信息（数据库 包括访问密码等），如下所示：
```yaml
consts:
  mongo:
    host: localhost
  mongo1:
    host: 10.208.61.117
    port: 20000
    username: xxxx
    password: xxxxx
    auth_db: admin
  mongo2:
    host: 10.60.1.145
  click1:
    host: 10.208.57.5
    tcp_port: 59000
  es1:
    host: '10.208.61.117'
    port: 9200
    username: xxxxx
    password: xxxxx
  qdrant:
    host: 10.60.1.145
    port: 6333
```

在其他流程中进行引用，比如：
```yaml
**from: db_envs.yaml**

consts:
  mongo2:
    database: global-news
    collection: news
  qdrant:
    collection: chunk_news_v2
  es1:
    index: goinv3_document_news
```

两个yaml文件会进行自动合并，然后就可以使用 `mongo2` `es1` 等变量
